# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FontShow' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FontShow
  
  pod 'IQKeyboardManager'


  target 'FontShowTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FontShowUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
